// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MakeMovies.Api.Meta.Tmdb.Three.Find.Item {
    public enum GetExternal_sourceQueryParameterType {
        [EnumMember(Value = "imdb_id")]
        Imdb_id,
        [EnumMember(Value = "facebook_id")]
        Facebook_id,
        [EnumMember(Value = "instagram_id")]
        Instagram_id,
        [EnumMember(Value = "tvdb_id")]
        Tvdb_id,
        [EnumMember(Value = "tiktok_id")]
        Tiktok_id,
        [EnumMember(Value = "twitter_id")]
        Twitter_id,
        [EnumMember(Value = "wikidata_id")]
        Wikidata_id,
        [EnumMember(Value = "youtube_id")]
        Youtube_id,
    }
}
