/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createProblemDetailsFromDiscriminatorValue, type ProblemDetails } from '../../../../../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1/movie/{id}/image
 */
export interface ImageRequestBuilder extends BaseRequestBuilder<ImageRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<string>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<string | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ImageRequestBuilderUriTemplate = "{+baseurl}/api/v1/movie/{id}/image";
/**
 * Metadata for all the requests in the request builder.
 */
export const ImageRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ImageRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "string",
    },
};
/* tslint:enable */
/* eslint-enable */
