export * from './genre.service';
import { GenreService } from './genre.service';
export * from './movies.service';
import { MoviesService } from './movies.service';
export * from './scrape.service';
import { ScrapeService } from './scrape.service';
export * from './torrent.service';
import { TorrentService } from './torrent.service';
export * from './transmission.service';
import { TransmissionService } from './transmission.service';
export const APIS = [GenreService, MoviesService, ScrapeService, TorrentService, TransmissionService];
