/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/';
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';

/**
 * Instantiates a new {@link MakeMoviesClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
export function createMakeMoviesClient(requestAdapter: RequestAdapter) {
    registerDefaultSerializer(JsonSerializationWriterFactory);
    registerDefaultDeserializer(JsonParseNodeFactory);
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<MakeMoviesClient>(requestAdapter, pathParameters, MakeMoviesClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface MakeMoviesClient extends BaseRequestBuilder<MakeMoviesClient> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MakeMoviesClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MakeMoviesClientNavigationMetadata: Record<Exclude<keyof MakeMoviesClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
