// tslint:disable
/**
 * Public Molly's Movies API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Torrent
 */
export interface Torrent {
    /**
     * 
     * @type {string}
     * @memberof Torrent
     */
    source?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Torrent
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Torrent
     */
    hash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Torrent
     */
    quality?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Torrent
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Torrent
     */
    sizeBytes?: number;
}


