// <auto-generated/>

using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using MakeMovies.Api.Meta.Tmdb.Three.Find.Item;

namespace MakeMovies.Api.Meta.Tmdb.Three.Find {
    /// <summary>
    /// Builds and executes requests for operations under \3\find
    /// </summary>
    public class FindRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the MakeMovies.Meta.Tmdb.Three.find.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithExternal_ItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("external_id", position);
            return new WithExternal_ItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new FindRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/find", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new FindRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FindRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/3/find", rawUrl) {
        }
    }
}
