/*
 * Public Molly's Movies API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MollysMovies.Client.Client.FileParameter;
using OpenAPIDateConverter = MollysMovies.Client.Client.OpenAPIDateConverter;

namespace MollysMovies.Client.Model
{
    /// <summary>
    /// Defines MoviesOrderBy
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MoviesOrderBy
    {
        /// <summary>
        /// Enum Title for value: Title
        /// </summary>
        [EnumMember(Value = "Title")]
        Title = 1,

        /// <summary>
        /// Enum Year for value: Year
        /// </summary>
        [EnumMember(Value = "Year")]
        Year = 2,

        /// <summary>
        /// Enum Rating for value: Rating
        /// </summary>
        [EnumMember(Value = "Rating")]
        Rating = 3

    }

}
