/*
 * Public Molly's Movies API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MollysMovies.Client.Client.FileParameter;
using OpenAPIDateConverter = MollysMovies.Client.Client.OpenAPIDateConverter;

namespace MollysMovies.Client.Model
{
    /// <summary>
    /// Defines MovieDownloadStatusCode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum MovieDownloadStatusCode
    {
        /// <summary>
        /// Enum Started for value: Started
        /// </summary>
        [EnumMember(Value = "Started")]
        Started = 1,

        /// <summary>
        /// Enum Downloaded for value: Downloaded
        /// </summary>
        [EnumMember(Value = "Downloaded")]
        Downloaded = 2,

        /// <summary>
        /// Enum Complete for value: Complete
        /// </summary>
        [EnumMember(Value = "Complete")]
        Complete = 3

    }

}
