/*
 * Public Molly's Movies API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MollysMovies.Client.Client.FileParameter;
using OpenAPIDateConverter = MollysMovies.Client.Client.OpenAPIDateConverter;

namespace MollysMovies.Client.Model
{
    /// <summary>
    /// Defines ScraperType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScraperType
    {
        /// <summary>
        /// Enum Local for value: Local
        /// </summary>
        [EnumMember(Value = "Local")]
        Local = 1,

        /// <summary>
        /// Enum Torrent for value: Torrent
        /// </summary>
        [EnumMember(Value = "Torrent")]
        Torrent = 2

    }

}
