/*
 * Public Molly's Movies API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MollysMovies.Client.Client.FileParameter;
using OpenAPIDateConverter = MollysMovies.Client.Client.OpenAPIDateConverter;

namespace MollysMovies.Client.Model
{
    /// <summary>
    /// Scrape
    /// </summary>
    [DataContract(Name = "Scrape")]
    public partial class Scrape : IEquatable<Scrape>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Scrape" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="startDate">startDate.</param>
        /// <param name="endDate">endDate.</param>
        /// <param name="success">success.</param>
        /// <param name="localMovieCount">localMovieCount.</param>
        /// <param name="movieCount">movieCount.</param>
        /// <param name="torrentCount">torrentCount.</param>
        /// <param name="sources">sources.</param>
        public Scrape(string? id = default(string?), DateTime startDate = default(DateTime), DateTime? endDate = default(DateTime?), bool? success = default(bool?), int localMovieCount = default(int), int movieCount = default(int), int torrentCount = default(int), List<ScrapeSource> sources = default(List<ScrapeSource>))
        {
            this.Id = id;
            this.StartDate = startDate;
            this.EndDate = endDate;
            this.Success = success;
            this.LocalMovieCount = localMovieCount;
            this.MovieCount = movieCount;
            this.TorrentCount = torrentCount;
            this.Sources = sources;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public string? Id { get; set; }

        /// <summary>
        /// Gets or Sets StartDate
        /// </summary>
        [DataMember(Name = "startDate", EmitDefaultValue = false)]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or Sets EndDate
        /// </summary>
        [DataMember(Name = "endDate", EmitDefaultValue = true)]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool? Success { get; set; }

        /// <summary>
        /// Gets or Sets LocalMovieCount
        /// </summary>
        [DataMember(Name = "localMovieCount", EmitDefaultValue = false)]
        public int LocalMovieCount { get; set; }

        /// <summary>
        /// Gets or Sets MovieCount
        /// </summary>
        [DataMember(Name = "movieCount", EmitDefaultValue = false)]
        public int MovieCount { get; set; }

        /// <summary>
        /// Gets or Sets TorrentCount
        /// </summary>
        [DataMember(Name = "torrentCount", EmitDefaultValue = false)]
        public int TorrentCount { get; set; }

        /// <summary>
        /// Gets or Sets Sources
        /// </summary>
        [DataMember(Name = "sources", EmitDefaultValue = true)]
        public List<ScrapeSource> Sources { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Scrape {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  LocalMovieCount: ").Append(LocalMovieCount).Append("\n");
            sb.Append("  MovieCount: ").Append(MovieCount).Append("\n");
            sb.Append("  TorrentCount: ").Append(TorrentCount).Append("\n");
            sb.Append("  Sources: ").Append(Sources).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Scrape);
        }

        /// <summary>
        /// Returns true if Scrape instances are equal
        /// </summary>
        /// <param name="input">Instance of Scrape to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Scrape input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.EndDate == input.EndDate ||
                    (this.EndDate != null &&
                    this.EndDate.Equals(input.EndDate))
                ) && 
                (
                    this.Success == input.Success ||
                    (this.Success != null &&
                    this.Success.Equals(input.Success))
                ) && 
                (
                    this.LocalMovieCount == input.LocalMovieCount ||
                    this.LocalMovieCount.Equals(input.LocalMovieCount)
                ) && 
                (
                    this.MovieCount == input.MovieCount ||
                    this.MovieCount.Equals(input.MovieCount)
                ) && 
                (
                    this.TorrentCount == input.TorrentCount ||
                    this.TorrentCount.Equals(input.TorrentCount)
                ) && 
                (
                    this.Sources == input.Sources ||
                    this.Sources != null &&
                    input.Sources != null &&
                    this.Sources.SequenceEqual(input.Sources)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.StartDate != null)
                {
                    hashCode = (hashCode * 59) + this.StartDate.GetHashCode();
                }
                if (this.EndDate != null)
                {
                    hashCode = (hashCode * 59) + this.EndDate.GetHashCode();
                }
                if (this.Success != null)
                {
                    hashCode = (hashCode * 59) + this.Success.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LocalMovieCount.GetHashCode();
                hashCode = (hashCode * 59) + this.MovieCount.GetHashCode();
                hashCode = (hashCode * 59) + this.TorrentCount.GetHashCode();
                if (this.Sources != null)
                {
                    hashCode = (hashCode * 59) + this.Sources.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
