/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { DownloadRequestBuilderRequestsMetadata, type DownloadRequestBuilder } from './download/';
import { GenreRequestBuilderRequestsMetadata, type GenreRequestBuilder } from './genre/';
import { LibraryRequestBuilderRequestsMetadata, type LibraryRequestBuilder } from './library/';
import { MovieRequestBuilderNavigationMetadata, MovieRequestBuilderRequestsMetadata, type MovieRequestBuilder } from './movie/';
import { ScrapeRequestBuilderRequestsMetadata, type ScrapeRequestBuilder } from './scrape/';
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/v1
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The download property
     */
    get download(): DownloadRequestBuilder;
    /**
     * The genre property
     */
    get genre(): GenreRequestBuilder;
    /**
     * The library property
     */
    get library(): LibraryRequestBuilder;
    /**
     * The movie property
     */
    get movie(): MovieRequestBuilder;
    /**
     * The scrape property
     */
    get scrape(): ScrapeRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/api/v1";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    download: {
        requestsMetadata: DownloadRequestBuilderRequestsMetadata,
    },
    genre: {
        requestsMetadata: GenreRequestBuilderRequestsMetadata,
    },
    library: {
        requestsMetadata: LibraryRequestBuilderRequestsMetadata,
    },
    movie: {
        requestsMetadata: MovieRequestBuilderRequestsMetadata,
        navigationMetadata: MovieRequestBuilderNavigationMetadata,
    },
    scrape: {
        requestsMetadata: ScrapeRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
