// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace MakeMovies.Api.Meta.Tmdb.Three.Configuration {
    public class ConfigurationGetResponse : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The change_keys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ChangeKeys { get; set; }
#nullable restore
#else
        public List<string> ChangeKeys { get; set; }
#endif
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ConfigurationGetResponse_images? Images { get; set; }
#nullable restore
#else
        public ConfigurationGetResponse_images Images { get; set; }
#endif
        /// <summary>
        /// Instantiates a new configurationGetResponse and sets the default values.
        /// </summary>
        public ConfigurationGetResponse() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static ConfigurationGetResponse CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new ConfigurationGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"change_keys", n => { ChangeKeys = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"images", n => { Images = n.GetObjectValue<ConfigurationGetResponse_images>(ConfigurationGetResponse_images.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("change_keys", ChangeKeys);
            writer.WriteObjectValue<ConfigurationGetResponse_images>("images", Images);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
